[project]
name = "raite"
version = "0.0.1"
description = ""
authors = [
    {name = "James Sweet", email = "james.sweet@protonmail.com"},
]
dependencies = [
    "vidgear>=0.3.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

